import { MetadataRoute } from 'next'

export default function sitemap(): MetadataRoute.Sitemap {
  const baseUrl = 'https://etfpruvodce.cz'
  
  // Static pages
  const staticPages = [
    '',
    '/co-jsou-etf',
    '/co-jsou-etf/jak-zacit-investovat',
    '/kde-koupit-etf',
    '/srovnani-etf',
    '/srovnani-brokeru',
    '/portfolio-strategie',
    '/portfolio-strategie/akciove-portfolio',
    '/portfolio-strategie/dividendove-portfolio',
    '/portfolio-strategie/nobel-portfolio',
    '/portfolio-strategie/permanentni-portfolio',
    '/portfolio-strategie/ray-dalio-all-weather',
    '/kalkulacky',
    '/kalkulacky/hypotecni-kalkulacka',
    '/kalkulacky/cisty-plat-2025',
    '/kalkulacky/uverova-kalkulacka',
    '/kalkulacky/investicni-kalkulacka',
    '/kalkulacky/monte-carlo-simulator',
    '/kalkulacky/fire-kalkulacka',
    '/kalkulacky/nouzova-rezerva',
    '/kalkulacky/kalkulacka-poplatku-etf',
    '/kalkulacky/kurzovy-dopad-etf',
    '/nejlepsi-etf',
    '/nejlepsi-etf/nejlepsi-etf-2025',
    '/nejlepsi-etf/nejlevnejsi-etf',
    '/nejlepsi-etf/etf-zdarma-degiro',
    '/nejlepsi-etf/nejlepsi-celosvetove-etf',
    '/nejlepsi-etf/nejlepsi-sp500-etf',
    '/nejlepsi-etf/nejlepsi-msci-world-etf',
    '/nejlepsi-etf/nejlepsi-nasdaq-etf',
    '/nejlepsi-etf/nejlepsi-dax-etf',
    '/nejlepsi-etf/nejlepsi-stoxx600-etf',
    '/nejlepsi-etf/nejlepsi-ftse100-etf',
    '/nejlepsi-etf/nejlepsi-americke-etf',
    '/nejlepsi-etf/nejlepsi-evropske-etf',
    '/nejlepsi-etf/nejlepsi-asijsko-pacificke-etf',
    '/nejlepsi-etf/nejlepsi-japonske-etf',
    '/nejlepsi-etf/nejlepsi-cinske-etf',
    '/nejlepsi-etf/nejlepsi-emerging-markets-etf',
    '/nejlepsi-etf/nejlepsi-dividendove-etf',
    '/nejlepsi-etf/nejlepsi-nemovitostni-etf',
    '/nejlepsi-etf/nejlepsi-dluhopisove-etf',
    '/nejlepsi-etf/nejlepsi-komoditni-etf',
    '/nejlepsi-etf/nejlepsi-zlate-etf',
    '/nejlepsi-etf/nejlepsi-technologicke-etf',
    '/nejlepsi-etf/nejlepsi-healthcare-etf',
    '/nejlepsi-etf/nejlepsi-financni-etf',
    '/nejlepsi-etf/nejlepsi-energeticke-etf',
    '/nejlepsi-etf/nejlepsi-spotrebni-etf',
    '/nejlepsi-etf/nejlepsi-ai-etf',
    '/nejlepsi-etf/nejlepsi-robotika-etf',
    '/nejlepsi-etf/nejlepsi-clean-energy-etf',
    '/nejlepsi-etf/nejlepsi-cloud-etf',
    '/nejlepsi-etf/nejlepsi-biotechnologie-etf',
    '/nejlepsi-etf/nejlepsi-kyberbezpecnost-etf',
    '/nejlepsi-etf/nejlepsi-defense-etf',
    '/nejlepsi-etf/nejlepsi-value-etf',
    '/nejlepsi-etf/nejlepsi-growth-etf',
    '/nejlepsi-etf/nejlepsi-small-cap-etf',
    '/nejlepsi-etf/nejlepsi-esg-etf',
    '/degiro-recenze',
    '/xtb-recenze',
    '/trading212-recenze',
    '/interactive-brokers-recenze',
    '/fio-ebroker-recenze',
    '/portu-recenze',
    '/infografiky'
  ]

  return staticPages.map((path) => ({
    url: `${baseUrl}${path}`,
    lastModified: new Date(),
    changeFrequency: path === '' ? 'daily' : path.includes('/kalkulacky') ? 'weekly' : 'monthly',
    priority: path === '' ? 1 : path.includes('/nejlepsi-etf') || path.includes('/srovnani') ? 0.9 : 0.8,
  }))
}