// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nbhwnatadyubiuadfakx.supabase.co";
// Modern publishable key (sb_publishable_...). Nahrazuje starý legacy anon JWT
// klíč, který Supabase zakázal ("Legacy API keys are disabled") – ten už vracel
// chybu při všech dotazech z prohlížeče.
const SUPABASE_PUBLISHABLE_KEY = "sb_publishable_IrdFtruv53Z2RbXNRRWCcw_K0TD4_ml";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);